name: PhpTonClient Ubuntu 20.04

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php-versions: ['7.4']
    name: PHP ${{ matrix.php-versions }} Test on ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ffi, json, zlib
          tools: composer
      - name: Install Dependencies
        run: composer install
      - name: Tests
        run: ./vendor/bin/phpunit tests/
